### ISSUE TITLE
Unable to turn TV on.

### ISSUE THREAD

**Issue by gm3197** [natalan/samsung-remote#12]
I am currently able to send all of the remote keys. I can change the volume, power off the tv, etc. However, I am unable to use this library to turn the tv back on once it has been turned off. I have used "KEY_POWER", "KEY_POWERON", and "KEY_PANEL_POWER", yet none of them will turn the tv back on. I simply get a timeout error. Thanks in advance.

**Comment by natalan** [comment]
Because of energy saving concerns, the network interface is deactivated once the TV is switched off. I believe this is true for pre-2016 TVs. Not sure about the latest models.
