### ISSUE TITLE
Wrong repository link in npm

### ISSUE THREAD

**Issue by atnartur** [natalan/samsung-remote#14]
On the npm package page https://www.npmjs.com/package/samsung-tv-remote there is the wrong link on github repository. Can you fix it, please?

**Comment by natalan** [comment]
Sorry, that's not the same module. This one is https://www.npmjs.com/package/samsung-remote

**Comment by peternewman** [comment]
FWIW the other one was https://github.com/Badisi/samsung-tv-remote and I've opened https://github.com/Badisi/samsung-tv-remote/pull/4 to fix it.
