### ISSUE TITLE
KEY_POWERON not working

### ISSUE THREAD

**Issue by anilktalla** [natalan/samsung-remote#3]
All the commands are working but if i turn off and turn it back on using KEY_POWERON tv is not turning on.

**Comment by trymbill** [comment]
Same here, can't get that to work.

**Comment by ghost** [comment]
That's actually not an issue of this module. The Network Interface is switched off with the TV and hence cannot receive or handle any power on requests. That's the same with most TVs, even professional displays. Some devices got an serial interface though, which will work most off the times.

**Comment by natalan** [comment]
As @jewepasch already stated, this is not an issue with the module, but rather with TV that cannot turn on over network interface.

**Comment by salimusta** [comment]
Same here. Try to ping the IP you ll see the TV goes Off line after KEY_POWEROFF
