### ISSUE TITLE
Use node-net-ping over System Call

### ISSUE THREAD

**Issue by MeFisto94** [natalan/samsung-remote#6]
In terms of Portability it is desirable to rather use the according node module which is dealing with the sockets itself rather than launching some shell command.

net-ping would work on Windows, Android, Browsers, etc. without us having to worry about how the commandline parameters are.

**Comment by natalan** [comment]
@MeFisto94 Feel free to make a PR with the change and I'll accept it. I don't have my Samsung TV anymore, so testing is problematic...

**Comment by MeFisto94** [comment]
I implemented it but I'm not going to PR it since net-ping relies on raw-sockets it needs root access which is completely pointless for a TV-Remote.

I will look into a ping wrapper which simply does what you did but takes care of different os's

**Comment by natalan** [comment]
Closing as part of #19
