### ISSUE TITLE
NOOB

### ISSUE THREAD

**Issue by bachoo786** [natalan/samsung-remote#9]
Hi
I have installed the npn install samsung-remote --save on my raspberry pi but I get the following errors:

`npm WARN saveError ENOENT: no such file or directory, open '/home/pi/package.json'
/home/pi
└── samsung-remote@1.2.5 

npm WARN enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN pi No description
npm WARN pi No repository field.
npm WARN pi No README data
npm WARN pi No license field.`

I am not sure what to do next; what is the usage section for?

Can someone please guide and help me?

Thanks.

**Comment by ahmadpak** [comment]
I have the same issue.

**Comment by william-seaton** [comment]
Try `npm init` and answer all the prompts.  Then try `npm install --save samsung-remote`
